
@url = https://108yn5o0v0.execute-api.eu-west-1.amazonaws.com/prod/

GET {{ url }}/empl?id=26275131
###

POST {{ url }}/empl
content-type: application/json

{
    "name": "Pawel P",
    "position": "DE",
    "nationality": "polish"
}
###

POST {{ url }}/empl?name=Edgar&position=worker

###


"4c1b564c-2300-488c-ad4f-31a65d6e2498"


###

GET {{ url }}/empl?id=4c1b564c-2300-488c-ad4f-31a65d6e2498
###

GET {{ url }}/empl?id=8013fa56-f11c-4a65-8538-2b38f2d828cb
###

GET {{ url }}/empl?id=a3fb1885-1dc6-4050-b521-6972bf1894ef
###